spring.application.name=backend

# KET NOI NEON.TECH (AWS SINGAPORE - CUC NHANH)
spring.datasource.url=jdbc:postgresql://ep-aged-sunset-a1n5w3bm-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&connectTimeout=60&socketTimeout=60
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oKYfeq0hOB9w
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.docker.compose.enabled=false

app.seed-data=false

# HikariCP Configuration for Neon (Serverless Postgres) - Hardened Settings
spring.datasource.hikari.connection-timeout=90000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.initialization-fail-timeout=0

# JWT Configuration
jwt.secret=FloodRescueSecretKeyForJWTTokenGeneration2026
jwt.expiration=86400000

server.port=8080
app.upload-dir=uploads

# ===============================
# Cloudflare R2 configuration
# ===============================

r2.bucket-name=flood-rescue-media

r2.endpoint=https://f51c459991d7230cc196c83f4f97934f.r2.cloudflarestorage.com

r2.access-key=8d81836965565765a466811de4f784f2
r2.secret-key=d2992bd269fe25b6cf6a565b988574dff1c028340f93175ee341b6282bba8f04

r2.public-base-url=https://pub-4c9dcba3185a4c28b9168edb655675a2.r2.dev
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB